apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dex-virtualservice
  namespace: kyma-system
  labels:
    app: dex
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  hosts:
  - "dex.{{ .Values.global.domainName }}"
  gateways:
  - {{ .Values.global.istio.gateway.namespace }}/{{ .Values.global.istio.gateway.name }}
  http:
  - match:
    - uri:
        regex: /.*
    route:
    - destination:
        port:
          number: {{ .Values.containerPort }}
        host: dex-service
      headers:
        response:
          add:
            "Vary": "Origin"
    corsPolicy:
      allowOrigins:
      - regex: ".*"
